spring.application.name=pio-pix
spring.datasource.url=jdbc:postgresql://db:5432/pio-pix
spring.datasource.username=pio_user
spring.datasource.password=pio_user
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.redis.timeout=2000
spring.cache.redis.time-to-live=100000
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.show-sql=true
server.port=9090
keySetURI=http://auth:8080/oauth2/jwks
logging.level.pro.sky.pio_pix=TRACE
